### ISSUE TITLE
Killbill.properties and Test

### ISSUE THREAD

**Issue by andreyunugro** [killbill/killbill-hello-world-ruby-plugin#1]
Hi,
These maybe minor issues. 
1. When I build and test this plugin, the result is OK with 0 failures, but when I plug it into killbill (0.11.3), the log says: 
NameError: uninitialized constant Killbill::Hello 
[main] WARN  o.killbill.billing.osgi.FileInstall - Unable to start bundle.
My current solution: 
modify killbill.properties, change this line
"mainClass=Killbill::Hello::HelloWorldPlugin" with
"mainClass=Killbill::HelloWorld::HelloWorldPlugin"
and rebuild.
2. Related to test, the plugin need to add test related to http route get /plugins/killbill-helloworld/users/:id, after user creation. Because when I try to test it manually, the output is Error "can't convert Symbol into Integer".
3. If someone (like me) create users table manually using ddl.sql, the create query will fail because of comma char at the end of UNIQUE KEY.
Thank you..

**Comment by pierre** [comment]
> 1. When I build and test this plugin, the result is OK with 0 failures, but when I plug it into killbill (0.11.3), the log says: 
>    NameError: uninitialized constant Killbill::Hello 
>    [main] WARN o.killbill.billing.osgi.FileInstall - Unable to start bundle.
>    My current solution: 
>    modify killbill.properties, change this line
>    "mainClass=Killbill::Hello::HelloWorldPlugin" with
>    "mainClass=Killbill::HelloWorld::HelloWorldPlugin"
>    and rebuild.

You're right - fixed.

> 1. Related to test, the plugin need to add test related to http route get /plugins/killbill-helloworld/users/:id, after user creation. Because when I try to test it manually, the output is Error "can't convert Symbol into Integer".

I wasn't able to reproduce this, do you have the stacktrace?

> 1. If someone (like me) create users table manually using ddl.sql, the create query will fail because of comma char at the end of UNIQUE KEY.

Ah yes, typo - fixed.

> Thank you..

Thanks for the reports!
